FROM almalinux:8
ARG user=ansible
RUN dnf update -y && dnf install -y openssh-server sudo wget yum-utils make gcc openssl-devel bzip2-devel libffi-devel zlib-devel 
RUN wget https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tgz && \
    tar xzf Python-3.10.5.tgz && \
    cd Python-3.10.5 && \
    ./configure --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions && \
    make -j ${nproc} && \
    make altinstall 
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN useradd -m -s /bin/bash ${user} && \
    echo "${user}:password" | chpasswd && \
    echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
ADD ssh/id_rsa.pub /home/${user}/.ssh/authorized_keys
RUN chown -R ${user}:${user} /home/${user}/.ssh
RUN mkdir -p /run/sshd && ssh-keygen -A
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
