services:
  alma-1:
    image: node-alma:v1
    container_name: alma-1
    networks:
      - vnet

  alma-2:
    image: node-alma:v1
    container_name: alma-2
    networks:
      - vnet

  ubuntu-1:
    image: node-ubuntu:v1
    container_name: ubuntu-1
    networks:
      - vnet
  
  ubuntu-2:
    image: node-ubuntu:v1
    container_name: ubuntu-2
    volumes:
      - ./controller-workspace:/root/controller-workspace
    networks:
      - vnet
  
  ansible-controller:
    image: ansible-controller:v1
    container_name: controller
    volumes:
      - ./controller-workspace:/root/controller-workspace
    command: tail -f /dev/null
    networks:
      - vnet

networks:
  vnet:
    driver: bridge